# Generated by Django 3.0.3 on 2020-02-09 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departamentos',
            new_name='Departamento',
        ),
        migrations.RenameModel(
            old_name='Empresas',
            new_name='Empresa',
        ),
    ]
