# Generated by Django 3.0.3 on 2020-02-09 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_funcionario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Funcionario',
        ),
    ]
